### ISSUE TITLE
I can not execute script because of errors HELP ME

### ISSUE THREAD

**Issue by xraphaelx** [JaganGanesh/Twitter-Bot#1]
![error](https://user-images.githubusercontent.com/10857482/52367679-c3e87180-2a33-11e9-83ba-6d6544c0849f.png)

**Comment by JaganGanesh** [comment]
Hello Raphael,
I couldn't understand the problem here, It seems to be working on my system. Try this and let me know if you still have problem.

1. Clone the repository again and install twit manually.
``` bash
git clone https://github.com/JaganGanesh/Twitter-Bot.git

cd Twitter-Bot

npm install --save twit
```

2. Add *consumer_key*, *consumer_secret*, *access_token* and *access_token_secret* to config.js

3. Run bot.js (*don't use sudo*).
``` bash
node bot.js
```

If you still get errors, Please switch back to the previous commit **[Initial Release](https://github.com/JaganGanesh/Twitter-Bot/commit/f0d90882fad3f2b8191b5c1f1db75535ad234651)** and try again.

*I will revisit the code this weekend.*
